model: "gpt-oss-120b"
api_base: "http://10.211.37.7:9021"  # Replace with your actual endpoint
api_key: "EMPTY"
instances: 1
per_instance_max_parallel_requests: 10
request_timeout: 120
max_retries: 6
retry_delay: 4
temperature: 0.0
top_p: 0.9
max_tokens: 32000